
use courseDataBase;
create database xxx;
use xxx;
ALTER TABLE HOSPITAL
  DROP COLUMN REGISTRATION_PHONE;
  ALTER TABLE HOSPITAL
    DROP COLUMN HEAD_PHYSICIAN;         
DROP TABLE HOSPITAL;


ALTER TABLE dbo.doc_exy ALTER COLUMN column_a DECIMAL (5, 2) ;  

ALTER TABLE HOSPITAL ADD ID_DOCTOR INT REFERENCES DOCTOR(ID_DOCTOR) NOT NULL unique;

DROP TABLE HOSPITAL;

DROP TABLE DEPARTMENT;
DROP TABLE DOCTOR;

DROP TABLE PATIENT;
DROP TABLE RECEPTION;
DROP TABLE TIME_TIMETABLE;


create table HOSPITAL(
ID_HOSPITAL INT PRIMARY KEY IDENTITY,
COUNTRY nvarchar(40) NOT NULL,
CITY nvarchar(40) NOT NULL,
AREA nvarchar(40) NOT NULL,
NAME_HOSPITAL nvarchar(60) NOT NULL,
REGISTRATION_PHONE nvarchar(10) NOT NULL);

create table DEPARTMENT (
ID_DEPARTMENT INT PRIMARY KEY IDENTITY,
NAME_DEPARTMENT NVARCHAR(30) NOT NULL,
ID_HOSPITAL INT REFERENCES HOSPITAL(ID_HOSPITAL) ON DELETE CASCADE NOT NULL);


CREATE TABLE PATIENT(
ID_PATIENT INT PRIMARY KEY IDENTITY,
GENDER CHAR(1) DEFAULT 'M' CHECK (GENDER in('M','W')) not null,
FIRST_NAME NVARCHAR(20) NOT NULL,
LAST_NAME NVARCHAR(20) NOT NULL,
PATRONY NVARCHAR(20) NOT NULL,
BDAY DATE NOT NULL,
HOME_ADRESS varchar(100)  NOT NULL,
PASSPORT_ID varchar(100)  NULL,
ID_HOSPITAL INT REFERENCES HOSPITAL(ID_HOSPITAL) ON DELETE CASCADE NOT NULL,
PLACE_OF_WORK_OR_STUDY NVARCHAR(40) DEFAULT '---',
DISABILITY NVARCHAR(40) DEFAULT '---',
CHRONIC_DISEASES NVARCHAR(40) DEFAULT '---');

CREATE TABLE SPECIALTY(
ID_SPECIALTY INT PRIMARY KEY IDENTITY,
ID_DOCTOR INT REFERENCES DOCTOR(ID_DOCTOR)  ON DELETE CASCADE NOT NULL,
SPECIALTY_NAME NVARCHAR(50) NOT NULL)

ALTER TABLE DOCTOR ALTER COLUMN ID_DEPARTMENT INT;  

CREATE TABLE DOCTOR(
ID_DOCTOR INT PRIMARY KEY IDENTITY,
ID_DEPARTMENT INT REFERENCES DEPARTMENT(ID_DEPARTMENT)  ,
FIRST_NAME NVARCHAR(20) NOT NULL,
LAST_NAME NVARCHAR(20) NOT NULL,
PATRONY NVARCHAR(20) NOT NULL,
OFFICE NVARCHAR(10)NOT NULL,
QUALIFICATION NVARCHAR(30) NOT NULL,
BDAY DATE NOT NULL,
DATE_STARTED DATE NOT NULL,
POSITION NVARCHAR(20) not null,
PHONE_NUMBER NVARCHAR(20)  null,
ID_HOSPITAL INT REFERENCES HOSPITAL(ID_HOSPITAL)  NOT NULL 
);

CREATE TABLE TIME_TIMETABLE(
ID_TIME INT PRIMARY KEY IDENTITY,
ID_DOCTOR INT REFERENCES DOCTOR(ID_DOCTOR)  NOT NULL,
DAY_OF_THE_WEEK DATE not null,
STARTING_A_PATIENT_RECEPTION NVARCHAR(20) not null
);

CREATE TABLE  RECEPTION(
ID_RECEPTION INT PRIMARY KEY IDENTITY,
ID_DOCTOR INT REFERENCES DOCTOR(ID_DOCTOR)  NOT NULL,
ID_PATIENT INT REFERENCES PATIENT(ID_PATIENT)  NOT NULL,
ID_HOSPITAL INT REFERENCES HOSPITAL(ID_HOSPITAL) ON DELETE CASCADE NOT NULL,
ID_TIME INT REFERENCES TIME_TIMETABLE(ID_TIME) ON DELETE CASCADE NOT NULL,
SYMPTOMS NVARCHAR(100) DEFAULT'---',
DIAGNOSIS NVARCHAR(100) NOT NULL,
MEDICINES NVARCHAR(100) NOT NULL,
COMMENTS NVARCHAR(200) DEFAULT'---');


CREATE TABLE PASSWORD_TABLE(
ID_PASSWORD INT PRIMARY KEY IDENTITY,
ID_DOCTOR INT REFERENCES DOCTOR(ID_DOCTOR) ON DELETE CASCADE,
ID_PATIENT INT REFERENCES PATIENT(ID_PATIENT) ON DELETE CASCADE,
USER_PASSWORD varbinary(128)  null);














                                                          